### ISSUE TITLE
Use jsoniter-scala instead of circe

### ISSUE THREAD

**Issue by plokhotnyuk** [Free2MoveApp/geo-scala#6]
The library supports Scala.JS and Scala Native platforms and shows the best in JVM world performance of parsing and serialization for floating point numbers. 

Below are results of benchmarks for [a sample](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/GeoJSONBenchmark.scala#L9) of [the GeoJSON model](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/GeoJSON.scala) using different JSON parsers including circe and circe with jsoniter-scala booster:

![image](https://user-images.githubusercontent.com/890289/185414474-ef10ff0e-5472-459d-9f99-a3b4de94f77e.png)

![image](https://user-images.githubusercontent.com/890289/185414563-cd80b60f-b635-4a68-a7da-90bea438a85e.png)

**Comment by satabin** [comment]
Hi @plokhotnyuk, thanks for the issue. I think we can add a jsoniter integration, the same way we did for circe. I must admit I don't have much experience with it now, but it shouldn't be a big problem. I will investigate.
